#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FALSE_SWIPE) \
    F(DRAGON_CLAW) \
    F(FLIP_TURN) \
    F(CALM_MIND) \
    F(RISING_VOLTAGE) \
    F(TOXIC) \
    F(ICE_FANG) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(TERRAIN_PULSE) \
    F(FIRE_FANG) \
    F(STOMPING_TANTRUM) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HEAT_WAVE) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(SUPERCELL_SLAM) \
    F(GIGA_DRAIN) \
    F(TAUNT) \
    F(ELECTROWEB) \
    F(WEATHER_BALL) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(KNOCK_OFF) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(AURA_SPHERE) \
    F(REFLECT) \
    F(ROCK_SLIDE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(TELEPORT) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(HIGH_HORSEPOWER) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(ENERGY_BALL) \
    F(LEECH_LIFE) \
    F(THIEF) \
    F(STEEL_WING) \
    F(EXPLOSION) \
    F(TEMPER_FLARE) \
    F(OVERHEAT) \
    F(LOW_KICK) \
    F(GRASSY_GLIDE) \
    F(VOLT_SWITCH) \
    F(U_TURN) \
    F(ICE_PUNCH) \
    F(THUNDER_PUNCH) \
    F(FIRE_PUNCH) \
    F(ICE_SPINNER) \
    F(THUNDER_FANG) \
    F(SNARL) \
    F(LIQUIDATION) \
    F(WILD_CHARGE) \
    F(DRAGON_PULSE) \
    F(STEEL_BEAM) \
    F(EARTH_POWER) \
    F(LOW_SWEEP) \
    F(SCALD) \
    F(FROST_BREATH) \
    F(BULLDOZE) \
    F(PSYSHIC_NOISE) \
    F(SCORCHING_SANDS) \
    F(DAZZLING_GLEAM) \
    F(FLASH_CANNON) \
    F(DUAL_CHOP) \
    F(STONE_EDGE) \
    F(ROOST) \
    F(GUNK_SHOT) \
    F(DRAGON_HAMMER) \
    F(POWER_WHIP) \
    F(SHADOW_CLAW) \
    F(NASTY_PLOT) \
    F(SWORDS_DANCE) \
    F(DRILL_PECK) \
    F(TAKE_FLIGHT) \

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
